-- Extensions
create extension if not exists "pgcrypto";

-- Tables
create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null,
  title text not null,
  description text null,
  date text not null,
  location text not null,
  location_url text null,
  image_url text null,
  slider_images text[] null,
  agenda jsonb null,
  theme_id text null,
  status text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendees (
  id uuid primary key default gen_random_uuid(),
  event_id uuid null references public.events(id) on delete cascade,
  name text not null,
  email text not null,
  whatsapp_number text null,
  response text null,
  link_shared boolean null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.short_urls (
  id bigint generated by default as identity primary key,
  short_id text not null,
  original_url text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  clicks integer null default 0,
  constraint short_urls_short_id_key unique (short_id)
);

-- Indexes
create index if not exists attendees_event_id_idx on public.attendees(event_id);
create index if not exists short_urls_expires_at_idx on public.short_urls(expires_at);

-- updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at
before update on public.events
for each row execute function public.set_updated_at();

-- Cleanup functions
create or replace function public.cleanup_expired_short_urls()
returns void
language plpgsql
as $$
begin
  delete from public.short_urls where expires_at < now();
end;
$$;

create or replace function public.clean_expired_events()
returns void
language plpgsql
as $$
begin
  -- If you later introduce an explicit event expiry, update this logic.
  -- Placeholder: no-op.
  return;
end;
$$;

-- RLS
alter table public.events enable row level security;
alter table public.attendees enable row level security;
alter table public.short_urls enable row level security;

-- Policies: events
create policy "events_select_own" on public.events
for select
to authenticated
using (user_id = auth.uid());

create policy "events_insert_own" on public.events
for insert
to authenticated
with check (user_id = auth.uid());

create policy "events_update_own" on public.events
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "events_delete_own" on public.events
for delete
to authenticated
using (user_id = auth.uid());

-- Policies: attendees
create policy "attendees_select_event_owner" on public.attendees
for select
to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = attendees.event_id
      and e.user_id = auth.uid()
  )
);

create policy "attendees_insert_event_owner" on public.attendees
for insert
to authenticated
with check (
  exists (
    select 1 from public.events e
    where e.id = attendees.event_id
      and e.user_id = auth.uid()
  )
);

create policy "attendees_update_event_owner" on public.attendees
for update
to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = attendees.event_id
      and e.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.events e
    where e.id = attendees.event_id
      and e.user_id = auth.uid()
  )
);

create policy "attendees_delete_event_owner" on public.attendees
for delete
to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = attendees.event_id
      and e.user_id = auth.uid()
  )
);

-- Policies: public RSVP read/update attendee by id (no auth)
create policy "attendees_public_read" on public.attendees
for select
to anon
using (true);

create policy "attendees_public_update_response" on public.attendees
for update
to anon
using (true)
with check (true);

-- Policies: public event read (no auth)
create policy "events_public_read" on public.events
for select
to anon
using (true);

-- Policies: short_urls public read/insert/update/delete (used by anon redirect)
create policy "short_urls_public_all" on public.short_urls
for all
to anon
using (true)
with check (true);

-- Grants (optional explicit)
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant execute on all functions in schema public to anon, authenticated;
